<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GCGD1P4" failures="0" tests="2" name="Dashboard.Create_Account_Test_Cases.TC_02_And_03_Verify_Successful_Account_Creation_With_Valid_Data" time="22.833" errors="1" timestamp="2025-09-12T14:35:30 IST" skipped="0">
  <testcase classname="Dashboard.Create_Account_Test_Cases.TC_02_And_03_Verify_Successful_Account_Creation_With_Valid_Data" name="TC_02_Verify_successful_account_creation_with_valid_data" time="6.962"/>
  <system-out/>
  <testcase classname="Dashboard.Create_Account_Test_Cases.TC_02_And_03_Verify_Successful_Account_Creation_With_Valid_Data" name="TC_03_Verify_account_created_via_email_link" time="15.871">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:233)
at java.base/java.util.ImmutableCollections$Map1.<init>(ImmutableCollections.java:1112)
at java.base/java.util.Map.of(Map.java:1365)
at org.openqa.selenium.remote.DriverCommand.GET(DriverCommand.java:180)
at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:313)
at Test.Dashboard.Actions_Class.Create_Account_Actions.validateEmailLink(Create_Account_Actions.java:69)
at Dashboard.Create_Account_Test_Cases.TC_02_And_03_Verify_Successful_Account_Creation_With_Valid_Data.TC_03_Verify_account_created_via_email_link(TC_02_And_03_Verify_Successful_Account_Creation_With_Valid_Data.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- TC_03_Verify_account_created_via_email_link -->
  <system-out/>
</testsuite> <!-- Dashboard.Create_Account_Test_Cases.TC_02_And_03_Verify_Successful_Account_Creation_With_Valid_Data -->
